### ISSUE TITLE
UnhandledPromiseRejectionWarning with cabal --seed

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-cli#128]
I'm getting the following whenever I try `cabal --seed` or equivalent:

```
➜  cabal --seed
(node:57977) UnhandledPromiseRejectionWarning: OpenError: IO error: lock /Users/todrobbins/.cabal/v1/archives/0201400f1aa2e3076a3f17f4521b2cc41e258c446cdaa44742afe6e1b9fd5f82/views/LOCK: Resource temporarily unavailable
    at /Users/todrobbins/.nvm/versions/node/v12.2.0/lib/node_modules/cabal/node_modules/level-packager/node_modules/levelup/lib/levelup.js:96:23
    at /Users/todrobbins/.nvm/versions/node/v12.2.0/lib/node_modules/cabal/node_modules/level-packager/node_modules/abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/todrobbins/.nvm/versions/node/v12.2.0/lib/node_modules/cabal/node_modules/level-packager/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
    at /Users/todrobbins/.nvm/versions/node/v12.2.0/lib/node_modules/cabal/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/todrobbins/.nvm/versions/node/v12.2.0/lib/node_modules/cabal/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:30:14
(node:57977) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea what I'm doing incorrectly? @noffle?

**Comment by todrobbins** [comment]
Let me try with node v11.0.0...

**Comment by todrobbins** [comment]
Ha! I had the cli open in another tab... Carry on!

**Comment by cblgh** [comment]
it'd be great if we handled that case more elegantly tho
