### ISSUE TITLE
Cabal (terminal) fails to start: ERR_INVALID_ARG_TYPE (v12 node)

### ISSUE THREAD

**Issue by decentral1se** [cabal-club/cabal-cli#220]
On latest Debian.

```
💻 nvm install 12
v12.22.12 is already installed.
Now using node v12.22.12 (npm v6.14.16)
💻 npm install --global cabal
npm WARN deprecated dat-dns@4.1.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
/home/d/.nvm/versions/node/v12.22.12/bin/cabal -> /home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/cli.js
npm WARN notsup Unsupported engine for nopt@7.1.0: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: nopt@7.1.0
npm WARN notsup Unsupported engine for abbrev@2.0.0: wanted: {"node":"^14.17.0 || ^16.13.0 || >=18.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: abbrev@2.0.0
+ cabal@14.1.2
updated 21 packages in 12.608s
💻 cabal cabal://324eee92611cd877841c4de9fd5253e9dba6033329a837ee5f01beb005dffb2f
buffer.js:358
    throw new ERR_INVALID_ARG_TYPE('size', 'number', size);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received undefined
    at Function.alloc (buffer.js:370:3)
    at Function.keyPair (/home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/simple-hypercore-protocol/lib/handshake.js:67:25)
    at Function.keyPair (/home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/simple-hypercore-protocol/index.js:234:22)
    at Function.keyPair (/home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/hypercore-protocol/index.js:398:16)
    at new Feed (/home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/hypercore/index.js:74:53)
    at Feed (/home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/hypercore/index.js:54:39)
    at /home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/multifeed/index.js:62:16
    at /home/d/.nvm/versions/node/v12.22.12/lib/node_modules/cabal/node_modules/multifeed/ready.js:7:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by ralphtheninja** [comment]
@cblgh You mean a `package-lock.json` in a dependency to `cabal-cli`?

**Comment by cblgh** [comment]
@ralphtheninja i mean a published version of `cabal-cli` will not have `package-lock.json` be used to determine which dependncies are downloaded whe running the command `npm install` afaiu

in our case, the culprit causing issues appears to have been https://github.com/emilbayes/noise-protocol/commit/2891a1fd59479916562883eeae55212cfab54762 i.e. `noise-protocol@3.0.1` has cabal working as intended (which appears to be the case when cloning cabal-cli and installing with `npm i` inside the repo folder) while having `noise-protocol@3.0.2` installed (as seems to be the case when running `npm i -g cabal`) causes the issue mentioned in the original post

**Comment by decentral1se** [comment]
Thank you @cblgh `npm install -g cabal@14.1.4-0` worked! **I'm in**.
