### ISSUE TITLE
Cabal binaries: "No native build was found for platform=linux ..."

### ISSUE THREAD

**Issue by decentral1se** [cabal-club/cabal-cli#221]
From https://cabal.chat/download.html, I tried the Linux binary:

```
💻 ./cabal
pkg/prelude/bootstrap.js:1244
      throw error;
      ^
Error: No native build was found for platform=linux arch=x64 runtime=node abi=64 uv=1 libc=glibc node=10.17.0
    loaded from: /snapshot/cabal-cli/node_modules/sodium-native

    at Function.load.path (/snapshot/cabal-cli/node_modules/node-gyp-build/index.js:59:9)
    at load (/snapshot/cabal-cli/node_modules/node-gyp-build/index.js:21:30)
    at Object.<anonymous> (/snapshot/cabal-cli/node_modules/sodium-native/index.js:1:101)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
```

I assume I'm missing sodium packages but not sure how to install on Debian?

**Comment by sorenpeter** [comment]
I'm getting the same error on MacOS BigSur. I presume it should have been included in the binary, but got left out by mistake?!

**Comment by cblgh** [comment]
oopf, these are old! sorry about the confusion y'all, we have been up to date on maintaining those binaries. until we have finished the push to cable we'll probably stick to npm-based cabal-cli releases to make life easier

appreciate the eyeballs on this tho, i updated the website to [remove that section](https://github.com/cabal-club/cabal-club.github.io/commit/7a5d95002137eb04b763854906c647d9dc8467ae)
