### ISSUE TITLE
Running two instances on same laptop

### ISSUE THREAD

**Issue by michielbdejong** [cabal-club/cabal-cli#225]
I'm trying to run two instances of cabal on the same laptop, but the second one crashes:
```
npx cabal cabal://628d1d75d1197fe05c650fb6b2d5a90171adb1185c0d89772db758b93803b94b?admin=d431586157ba4ed341883c41054c1a5779388236fe8e4c2736d10f7d2191efa1

/Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/levelup/lib/levelup.js:119
      return callback(new OpenError(err))
                      ^
Error [OpenError]: IO error: lock /Users/michiel/.cabal/v1/archives/628d1d75d1197fd05c650fb6b2d5690171adb5185c0d89772db758b93803b94b/views/LOCK: Resource temporarily unavailable
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/levelup/lib/levelup.js:119:23
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
Emitted 'error' event on LevelUP instance at:
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/levelup/lib/levelup.js:60:19
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/levelup/lib/levelup.js:119:14
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    [... lines matching original stack trace ...]
    at /Users/michiel/.npm/_npx/bf9e302668aa8d99/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}

Node.js v20.11.0
```

When I stop the first one and retry the second one, it succeeds. Is there a way to tell cabal not to use this default global resource?

**Comment by michielbdejong** [comment]
Ah, found it! Running both instances with  `npx cabal --temp cabal://628d1d75d1197fe05c650fb6b2d5a90171adb1185c0d89772db758b93803b94b?admin=d431586157ba4ed341883c41054c1a5779388236fe8e4c2736d10f7d2191efa1` works for this, now I can `/join default` in both terminal windows and the two can chat with each other.
